### ISSUE TITLE
ArgumentOutOfRangeException in VS Editor caused by NQuerySignatureHelpSource

### ISSUE THREAD

**Issue by dallmair** [terrajobst/nquery-vnext#55]
Editor content:
```
SELECT  *
FROM    Categories c
        INNER JOIN CustomerCustomerDemo ccd ON TO_STRING(c.CategoryID = ccd.CustomerID
```

Was thrown when I had the join condition without TO_STRING (i.e. `ON c.CategoryID = ccd.CustomerID`), then went right after the ON and typed `<space>TO_STR<Enter>(<Del>`.

Exception message: Specified argument was out of the range of valid values. (Parameter 'span')

```
   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)
   at Microsoft.VisualStudio.Text.Implementation.TextVersion.CreateTrackingSpan(Int32 start, Int32 length, SpanTrackingMode trackingMode)
   at NQuery.Authoring.VSEditorWpf.SignatureHelp.NQuerySignatureHelpSource.AugmentSignatureHelpSession(ISignatureHelpSession session, IList`1 signatures) in D:\Source\nquery-vnext\src\NQuery.Authoring.VSEditorWpf\SignatureHelp\NQuerySignatureHelpSource.cs:line 38
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.SignatureHelpSession.Recalculate()
   at NQuery.Authoring.VSEditorWpf.SignatureHelp.SignatureHelpManager.UpdateSession() in D:\Source\nquery-vnext\src\NQuery.Authoring.VSEditorWpf\SignatureHelp\SignatureHelpManager.cs:line 124
   at NQuery.Authoring.VSEditorWpf.SignatureHelp.SignatureHelpManager.TextBufferOnPostChanged(Object sender, EventArgs e) in D:\Source\nquery-vnext\src\NQuery.Authoring.VSEditorWpf\SignatureHelp\SignatureHelpManager.cs:line 51
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent(Object sender, EventHandler eventHandlers)
```

**Comment by terrajobst** [comment]
Hmm, I can't reproduce this:

![Animation](https://user-images.githubusercontent.com/5169960/159614849-c72d40e1-03ff-4811-933e-3d0e985b95d3.gif)

**Comment by dallmair** [comment]
Are you running it under the debugger? Repro works for me very time:

![Animation](https://user-images.githubusercontent.com/9481495/159689866-17b65e02-c27f-47a8-b09b-c2cc699eb5b5.gif)
